server:
  commitHash: 1234

  staging:
    minReplicas: 1
    maxReplicas: 2

  test:
    minReplicas: 1
    maxReplicas: 1

  dev:
    minReplicas: 1
    maxReplicas: 1

  production:
    minReplicas: 1
    maxRepicas: 2


NODE_ENV: development
image: 402432300121.dkr.ecr.us-west-2.amazonaws.com/blockcluster-web
