---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "server.name" . }}
  namespace: {{ template "server.namespace" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - dev.blockcluster.io
    secretName: blockcluster-ssl
  rules:
  - host: dev.blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}
          servicePort: 3000
