---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "server.name" . }}-ing
  namespace: {{ template "server.namespace" . }}
{{ include "server.ingress.annotations" . | indent 2 }}
spec:
{{- if eq .Values.NODE_ENV "staging" }}
  tls:
  - hosts:
    - blockcluster.io
    - www.blockcluster.io
    - staging.blockcluster.io
    secretName: blockcluster-ssl
  rules:
  - host: blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80
  - host: www.blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80
  - host: staging.blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80
{{- else }}
  tls:
  - hosts:
    - home-{{ .Values.NODE_ENV }}.blockcluster.io
    secretName: blockcluster-ssl
  rules:
  - host: home-{{ .Values.NODE_ENV }}.blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80

{{- end -}}
