---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.name" . }}
  namespace: {{ template "server.namespace" . }}
  labels:
    app: {{ template "server.app" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports: 
  - port: 3000
    targetPort: 3000
  selector:
    app: {{ template "server.app" . }}
